### ISSUE TITLE
Monitor not working with Cura 5.4.0 or 5.3.1

### ISSUE THREAD

**Issue by bjenner** [emtrax-ltd/Cura2MoonrakerPlugin#74]
I've just setup the Moonraker Plugin and its great so far, but I can't seem to get the webcam to work. All I see in the Monitor tab is 

Camera
Url: http://speeder-pad.local/cam? 

That is the correct url, but nothing appears. This is the first time I've tried setting this up so I'm not sure which version last worked, but I did try both Cura 5.3.1 and 5.4.0.

**Comment by 4rianton** [comment]
Hi @emtrax-ltd, thank you for the development of this plugin. I am also not able to view the camera in Octoprint but I see that you added the wont-fix label to this issue. Is that because there was an issue with the original reporter's post, or is it a known issue and it actually won't be fixed? Thank you.
